E
======================================================================
ERROR: perfect_rectangle_testSuite (unittest.loader._FailedTest.perfect_rectangle_testSuite)
----------------------------------------------------------------------
ImportError: Failed to import test module: perfect_rectangle_testSuite
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/unittest/loader.py", line 419, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/loader.py", line 362, in _get_module_from_name
    __import__(name)
  File "/app/perfect_rectangle_testSuite.py", line 4, in <module>
    print(is_perfect_rectangle(rectangles))
          ^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_perfect_rectangle' is not defined


----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
Command exited with non-zero status 1
	Command being timed: "python3 -m unittest discover -s . -p *test*.py"
	User time (seconds): 0.43
	System time (seconds): 0.35
	Percent of CPU this job got: 14%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:05.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 14848
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2497
	Voluntary context switches: 123
	Involuntary context switches: 212
	Swaps: 0
	File system inputs: 0
	File system outputs: 576
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
