{
    "entries": [
        {
            "id": "top_k_frequent_elements_148",
            "error_message": "\u274c\u203c Errore nel container top_k_frequent_elements_148 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/top_k_frequent_elements:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\ntop_k_frequent_elements.py\\ntop_k_frequent_elements_testSuite.py\\nutils\\n\\n./__pycache__:\\ntop_k_frequent_elements.cpython-311.pyc\\ntop_k_frequent_elements_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./top_k_frequent_elements_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/top_k_frequent_elements/output.log",
            "language": "python"
        },
        {
            "id": "max_profit_163",
            "error_message": "\u274c\u203c Errore nel container max_profit_163 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/max_profit:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nmax_profit.py\\nmax_profit_testSuite.py\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nmax_profit.cpython-311.pyc\\nmax_profit_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./max_profit_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/max_profit/output.log",
            "language": "python"
        },
        {
            "id": "k_closest_points_182",
            "error_message": "\u274c\u203c Errore nel container k_closest_points_182 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/k_closest_points:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nk_closest_points.py\\nk_closest_points_testSuite.py\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nk_closest_points.cpython-311.pyc\\nk_closest_points_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./k_closest_points_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/k_closest_points/output.log",
            "language": "python"
        },
        {
            "id": "search_rotated_sorted_array_192",
            "error_message": "\u274c\u203c Errore nel container search_rotated_sorted_array_192 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/search_rotated_sorted_array:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\nsearch_rotated_sorted_array.py\\nsearch_rotated_sorted_array_testSuite.py\\nutils\\n\\n./__pycache__:\\nsearch_rotated_sorted_array.cpython-311.pyc\\nsearch_rotated_sorted_array_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./search_rotated_sorted_array_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/search_rotated_sorted_array/output.log",
            "language": "python"
        },
        {
            "id": "secret_santa_193",
            "error_message": "\u274c\u203c Errore nel container secret_santa_193 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/secret_santa:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\nsecret_santa.py\\nsecret_santa_testSuite.py\\nutils\\n\\n./__pycache__:\\nsecret_santa.cpython-311.pyc\\nsecret_santa_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./secret_santa_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/secret_santa/output.log",
            "language": "python"
        },
        {
            "id": "subarray_with_sum_k_196",
            "error_message": "\u274c\u203c Errore nel container subarray_with_sum_k_196 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/subarray_with_sum_k:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\nsubarray_with_sum_k.py\\nsubarray_with_sum_k_testSuite.py\\nsubarray_with_sum_k_testSuite.py.backup\\nutils\\n\\n./__pycache__:\\nsubarray_with_sum_k.cpython-311.pyc\\nsubarray_with_sum_k_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./subarray_with_sum_k_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/subarray_with_sum_k/output.log",
            "language": "python"
        },
        {
            "id": "top_k_frequent_elements_197",
            "error_message": "\u274c\u203c Errore nel container top_k_frequent_elements_197 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/top_k_frequent_elements:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\ntop_k_frequent_elements.py\\ntop_k_frequent_elements_testSuite.py\\nutils\\n\\n./__pycache__:\\ntop_k_frequent_elements.cpython-311.pyc\\ntop_k_frequent_elements_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./top_k_frequent_elements_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/top_k_frequent_elements/output.log",
            "language": "python"
        },
        {
            "id": "trapped_watter_198",
            "error_message": "\u274c\u203c Errore nel container trapped_watter_198 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/trapped_watter:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\ntrapped_watter.py\\ntrapped_watter_testSuite.py\\ntrapped_watter_testSuite.py.backup\\nutils\\n\\n./__pycache__:\\ntrapped_watter_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./trapped_watter_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/trapped_watter/output.log",
            "language": "python"
        },
        {
            "id": "coin_change_200",
            "error_message": "\u274c\u203c Errore nel container coin_change_200 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/coin_change:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\ncoin_change.py\\ncoin_change_testSuite.py\\ncoin_change_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\ncoin_change.cpython-311.pyc\\ncoin_change_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./coin_change_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/coin_change/output.log",
            "language": "python"
        },
        {
            "id": "create_palindrom_202",
            "error_message": "\u274c\u203c Errore nel container create_palindrom_202 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/create_palindrom:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\ncreate_palindrom.py\\ncreate_palindrom_testSuite.py\\ncreate_palindrom_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\ncreate_palindrom.cpython-311.pyc\\ncreate_palindrom_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./create_palindrom_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/create_palindrom/output.log",
            "language": "python"
        },
        {
            "id": "interleaving_strings_203",
            "error_message": "\u274c\u203c Errore nel container interleaving_strings_203 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/interleaving_strings:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\ninterleaving_strings.py\\ninterleaving_strings_testSuite.py\\ninterleaving_strings_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\ninterleaving_strings.cpython-311.pyc\\ninterleaving_strings_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./interleaving_strings_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/interleaving_strings/output.log",
            "language": "python"
        },
        {
            "id": "jump_game_2_204",
            "error_message": "\u274c\u203c Errore nel container jump_game_2_204 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/jump_game_2:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\njump_game_2.py\\njump_game_2_testSuite.py\\njump_game_2_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\njump_game_2.cpython-311.pyc\\njump_game_2_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./jump_game_2_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/jump_game_2/output.log",
            "language": "python"
        },
        {
            "id": "longest_common_substring_206",
            "error_message": "\u274c\u203c Errore nel container longest_common_substring_206 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/longest_common_substring:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nlongest_common_substring.py\\nlongest_common_substring_testSuite.py\\nlongest_common_substring_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nlongest_common_substring.cpython-311.pyc\\nlongest_common_substring_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./longest_common_substring_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/longest_common_substring/output.log",
            "language": "python"
        },
        {
            "id": "longest_increasing_subsequence_207",
            "error_message": "\u274c\u203c Errore nel container longest_increasing_subsequence_207 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/longest_increasing_subsequence:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nlongest_increasing_subsequence.py\\nlongest_increasing_subsequence_testSuite.py\\nlongest_increasing_subsequence_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nlongest_increasing_subsequence.cpython-311.pyc\\nlongest_increasing_subsequence_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./longest_increasing_subsequence_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/longest_increasing_subsequence/output.log",
            "language": "python"
        },
        {
            "id": "max_profit_k_transactions_208",
            "error_message": "\u274c\u203c Errore nel container max_profit_k_transactions_208 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/max_profit_k_transactions:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nmax_profit_k_transactions.py\\nmax_profit_k_transactions_testSuite.py\\nmax_profit_k_transactions_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nmax_profit_k_transactions.cpython-311.pyc\\nmax_profit_k_transactions_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./max_profit_k_transactions_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/max_profit_k_transactions/output.log",
            "language": "python"
        },
        {
            "id": "max_subarray_sum_209",
            "error_message": "\u274c\u203c Errore nel container max_subarray_sum_209 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/max_subarray_sum:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nmax_subarray_sum.py\\nmax_subarray_sum_testSuite.py\\nmax_subarray_sum_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nmax_subarray_sum.cpython-311.pyc\\nmax_subarray_sum_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./max_subarray_sum_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/max_subarray_sum/output.log",
            "language": "python"
        },
        {
            "id": "number_of_decodings_211",
            "error_message": "\u274c\u203c Errore nel container number_of_decodings_211 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/number_of_decodings:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nnumber_of_decodings.py\\nnumber_of_decodings_testSuite.py\\nnumber_of_decodings_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nnumber_of_decodings.cpython-311.pyc\\nnumber_of_decodings_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./number_of_decodings_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/number_of_decodings/output.log",
            "language": "python"
        },
        {
            "id": "number_of_smses_212",
            "error_message": "\u274c\u203c Errore nel container number_of_smses_212 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/number_of_smses:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nnumber_of_smses.py\\nnumber_of_smses_testSuite.py\\nnumber_of_smses_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nnumber_of_smses.cpython-311.pyc\\nnumber_of_smses_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./number_of_smses_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/number_of_smses/output.log",
            "language": "python"
        },
        {
            "id": "transform_number_ascending_digits_216",
            "error_message": "\u274c\u203c Errore nel container transform_number_ascending_digits_216 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/transform_number_ascending_digits:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\ntransform_number_ascending_digits.py\\ntransform_number_ascending_digits_testSuite.py\\ntransform_number_ascending_digits_testSuite.py.backup\\nutils\\n\\n./__pycache__:\\ntransform_number_ascending_digits.cpython-311.pyc\\ntransform_number_ascending_digits_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./transform_number_ascending_digits_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/transform_number_ascending_digits/output.log",
            "language": "python"
        },
        {
            "id": "find_duplicates_220",
            "error_message": "\u274c\u203c Errore nel container find_duplicates_220 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_duplicates:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nfind_duplicates.py\\nfind_duplicates_testSuite.py\\nfind_duplicates_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nfind_duplicates.cpython-311.pyc\\nfind_duplicates_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./find_duplicates_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_duplicates/output.log",
            "language": "python"
        },
        {
            "id": "find_pairs_with_sum_k_221",
            "error_message": "\u274c\u203c Errore nel container find_pairs_with_sum_k_221 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_pairs_with_sum_k:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nfind_pairs_with_sum_k.py\\nfind_pairs_with_sum_k_testSuite.py\\nfind_pairs_with_sum_k_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nfind_pairs_with_sum_k.cpython-311.pyc\\nfind_pairs_with_sum_k_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./find_pairs_with_sum_k_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_pairs_with_sum_k/output.log",
            "language": "python"
        },
        {
            "id": "group_anagrams_222",
            "error_message": "\u274c\u203c Errore nel container group_anagrams_222 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/group_anagrams:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\ngroup_anagrams.py\\ngroup_anagrams_testSuite.py\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\ngroup_anagrams.cpython-311.pyc\\ngroup_anagrams_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./group_anagrams_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/group_anagrams/output.log",
            "language": "python"
        },
        {
            "id": "longest_substring_with_k_distinct_characters_223",
            "error_message": "\u274c\u203c Errore nel container longest_substring_with_k_distinct_characters_223 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/longest_substring_with_k_distinct_characters:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nlongest_substring_with_k_distinct_characters.py\\nlongest_substring_with_k_distinct_characters_testSuite.py\\nlongest_substring_with_k_distinct_characters_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nlongest_substring_with_k_distinct_characters.cpython-311.pyc\\nlongest_substring_with_k_distinct_characters_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./longest_substring_with_k_distinct_characters_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/longest_substring_with_k_distinct_characters/output.log",
            "language": "python"
        },
        {
            "id": "add_two_numbers_226",
            "error_message": "\u274c\u203c Errore nel container add_two_numbers_226 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/add_two_numbers:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nadd_two_numbers.py\\nadd_two_numbers_testSuite.py\\nadd_two_numbers_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nadd_two_numbers_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./add_two_numbers_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/add_two_numbers/output.log",
            "language": "python"
        },
        {
            "id": "is_ascending_ll_228",
            "error_message": "\u274c\u203c Errore nel container is_ascending_ll_228 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/is_ascending_ll:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nis_ascending_ll.py\\nis_ascending_ll_testSuite.py\\nis_ascending_ll_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nis_ascending_ll_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./is_ascending_ll_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/is_ascending_ll/output.log",
            "language": "python"
        },
        {
            "id": "intersecting_ll_227",
            "error_message": "\u274c\u203c Errore nel container intersecting_ll_227 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/intersecting_ll:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nintersecting_ll.py\\nintersecting_ll_testSuite.py\\nintersecting_ll_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nintersecting_ll.cpython-311.pyc\\nintersecting_ll_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./intersecting_ll_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/intersecting_ll/output.log",
            "language": "python"
        },
        {
            "id": "max_difference_subll_229",
            "error_message": "\u274c\u203c Errore nel container max_difference_subll_229 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/max_difference_subll:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nmax_difference_subll.py\\nmax_difference_subll_testSuite.py\\nmax_difference_subll_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nmax_difference_subll_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./max_difference_subll_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/max_difference_subll/output.log",
            "language": "python"
        },
        {
            "id": "merge_sorted_ll_230",
            "error_message": "\u274c\u203c Errore nel container merge_sorted_ll_230 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/merge_sorted_ll:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nmerge_sorted_ll.py\\nmerge_sorted_ll_testSuite.py\\nmerge_sorted_ll_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nmerge_sorted_ll_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./merge_sorted_ll_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/merge_sorted_ll/output.log",
            "language": "python"
        },
        {
            "id": "odd_even_ll_231",
            "error_message": "\u274c\u203c Errore nel container odd_even_ll_231 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/odd_even_ll:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nodd_even_ll.py\\nodd_even_ll_testSuite.py\\nodd_even_ll_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nodd_even_ll_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./odd_even_ll_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/odd_even_ll/output.log",
            "language": "python"
        },
        {
            "id": "remove_element_ll_233",
            "error_message": "\u274c\u203c Errore nel container remove_element_ll_233 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/remove_element_ll:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nremove_element_ll.py\\nremove_element_ll_testSuite.py\\nremove_element_ll_testSuite.py.backup\\nrun.sh\\nutils\\n\\n./__pycache__:\\nremove_element_ll_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./remove_element_ll_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/remove_element_ll/output.log",
            "language": "python"
        },
        {
            "id": "remove_duplicates_sorted_ll_232",
            "error_message": "\u274c\u203c Errore nel container remove_duplicates_sorted_ll_232 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/remove_duplicates_sorted_ll:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nremove_duplicates_sorted_ll.py\\nremove_duplicates_sorted_ll_testSuite.py\\nremove_duplicates_sorted_ll_testSuite.py.backup\\nrun.sh\\nutils\\n\\n./__pycache__:\\nremove_duplicates_sorted_ll_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./remove_duplicates_sorted_ll_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/remove_duplicates_sorted_ll/output.log",
            "language": "python"
        },
        {
            "id": "reverse_ll_234",
            "error_message": "\u274c\u203c Errore nel container reverse_ll_234 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/reverse_ll:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nreverse_ll.py\\nreverse_ll_testSuite.py\\nreverse_ll_testSuite.py.backup\\nrun.sh\\nutils\\n\\n./__pycache__:\\nreverse_ll_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./reverse_ll_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/reverse_ll/output.log",
            "language": "python"
        },
        {
            "id": "total_divisible_numbers_243",
            "error_message": "\u274c\u203c Errore nel container total_divisible_numbers_243 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/total_divisible_numbers:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\ntotal_divisible_numbers.py\\ntotal_divisible_numbers_testSuite.py\\ntotal_divisible_numbers_testSuite.py.backup\\nutils\\n\\n./__pycache__:\\ntotal_divisible_numbers.cpython-311.pyc\\ntotal_divisible_numbers_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./total_divisible_numbers_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/total_divisible_numbers/output.log",
            "language": "python"
        },
        {
            "id": "generate_parentheses_249",
            "error_message": "\u274c\u203c Errore nel container generate_parentheses_249 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/generate_parentheses:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\ngenerate_parentheses.py\\ngenerate_parentheses_testSuite.py\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\ngenerate_parentheses.cpython-311.pyc\\ngenerate_parentheses_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./generate_parentheses_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/generate_parentheses/output.log",
            "language": "python"
        },
        {
            "id": "jumping_numbers_250",
            "error_message": "\u274c\u203c Errore nel container jumping_numbers_250 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/jumping_numbers:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\njumping_numbers.py\\njumping_numbers_testSuite.py\\njumping_numbers_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\njumping_numbers.cpython-311.pyc\\njumping_numbers_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./jumping_numbers_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/jumping_numbers/output.log",
            "language": "python"
        },
        {
            "id": "estimate_pi_239",
            "error_message": "\u274c\u203c Errore nel container estimate_pi_239 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/estimate_pi:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nestimate_pi.py\\nestimate_pi_testSuite.py\\nestimate_pi_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nestimate_pi.cpython-311.pyc\\nestimate_pi_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./estimate_pi_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/estimate_pi/output.log",
            "language": "python"
        },
        {
            "id": "permutations_255",
            "error_message": "\u274c\u203c Errore nel container permutations_255 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/permutations:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\npermutations.py\\npermutations_testSuite.py\\npermutations_testSuite.py.backup\\nrun.sh\\nutils\\n\\n./__pycache__:\\npermutations.cpython-311.pyc\\npermutations_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./permutations_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/permutations/output.log",
            "language": "python"
        },
        {
            "id": "running_median_263",
            "error_message": "\u274c\u203c Errore nel container running_median_263 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/running_median:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\nrunning_median.py\\nrunning_median_testSuite.py\\nrunning_median_testSuite.py.backup\\nutils\\n\\n./__pycache__:\\nrunning_median.cpython-311.pyc\\nrunning_median_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./running_median_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/running_median/output.log",
            "language": "python"
        },
        {
            "id": "encoding_string_268",
            "error_message": "\u274c\u203c Errore nel container encoding_string_268 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/encoding_string:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nencoding_string.py\\nencoding_string_testSuite.py\\nencoding_string_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nencoding_string.cpython-311.pyc\\nencoding_string_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./encoding_string_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/encoding_string/output.log",
            "language": "python"
        },
        {
            "id": "reverse_string_271",
            "error_message": "\u274c\u203c Errore nel container reverse_string_271 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/reverse_string:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nreverse_string.py\\nreverse_string_testSuite.py\\nreverse_string_testSuite.py.backup\\nrun.sh\\nutils\\n\\n./__pycache__:\\nreverse_string.cpython-311.pyc\\nreverse_string_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./reverse_string_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/reverse_string/output.log",
            "language": "python"
        },
        {
            "id": "strong_password_checker_274",
            "error_message": "\u274c\u203c Errore nel container strong_password_checker_274 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/strong_password_checker:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\nstrong_password_checker.py\\nstrong_password_checker_testSuite.py\\nstrong_password_checker_testSuite.py.backup\\nutils\\n\\n./__pycache__:\\nstrong_password_checker.cpython-311.pyc\\nstrong_password_checker_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./strong_password_checker_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/strong_password_checker/output.log",
            "language": "python"
        },
        {
            "id": "zigzag_conversion_276",
            "error_message": "\u274c\u203c Errore nel container zigzag_conversion_276 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/zigzag_conversion:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\nutils\\nzigzag_conversion.py\\nzigzag_conversion_testSuite.py\\nzigzag_conversion_testSuite.py.backup\\n\\n./__pycache__:\\nzigzag_conversion.cpython-311.pyc\\nzigzag_conversion_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./zigzag_conversion_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/zigzag_conversion/output.log",
            "language": "python"
        },
        {
            "id": "find_kth_smallest_node_bst_278",
            "error_message": "\u274c\u203c Errore nel container find_kth_smallest_node_bst_278 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_kth_smallest_node_bst:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nfind_kth_smallest_node_bst.py\\nfind_kth_smallest_node_bst_testSuite.py\\nfind_kth_smallest_node_bst_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nfind_kth_smallest_node_bst.cpython-311.pyc\\nfind_kth_smallest_node_bst_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./find_kth_smallest_node_bst_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_kth_smallest_node_bst/output.log",
            "language": "python"
        },
        {
            "id": "diameter_of_binary_tree_277",
            "error_message": "\u274c\u203c Errore nel container diameter_of_binary_tree_277 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/diameter_of_binary_tree:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\ndiameter_of_binary_tree.py\\ndiameter_of_binary_tree_testSuite.py\\ndiameter_of_binary_tree_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\ndiameter_of_binary_tree.cpython-311.pyc\\ndiameter_of_binary_tree_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./diameter_of_binary_tree_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/diameter_of_binary_tree/output.log",
            "language": "python"
        },
        {
            "id": "find_max_branch_sum_279",
            "error_message": "\u274c\u203c Errore nel container find_max_branch_sum_279 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_max_branch_sum:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nfind_max_branch_sum.py\\nfind_max_branch_sum_testSuite.py\\nfind_max_branch_sum_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nfind_max_branch_sum.cpython-311.pyc\\nfind_max_branch_sum_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./find_max_branch_sum_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_max_branch_sum/output.log",
            "language": "python"
        },
        {
            "id": "find_max_path_sum_280",
            "error_message": "\u274c\u203c Errore nel container find_max_path_sum_280 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_max_path_sum:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nfind_max_path_sum.py\\nfind_max_path_sum_testSuite.py\\nfind_max_path_sum_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nfind_max_path_sum.cpython-311.pyc\\nfind_max_path_sum_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./find_max_path_sum_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_max_path_sum/output.log",
            "language": "python"
        },
        {
            "id": "find_second_largest_node_bst_282",
            "error_message": "\u274c\u203c Errore nel container find_second_largest_node_bst_282 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_second_largest_node_bst:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nfind_second_largest_node_bst.py\\nfind_second_largest_node_bst_testSuite.py\\nfind_second_largest_node_bst_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nfind_second_largest_node_bst.cpython-311.pyc\\nfind_second_largest_node_bst_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./find_second_largest_node_bst_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_second_largest_node_bst/output.log",
            "language": "python"
        },
        {
            "id": "find_second_largest_node_281",
            "error_message": "\u274c\u203c Errore nel container find_second_largest_node_281 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_second_largest_node:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\nfind_second_largest_node.py\\nfind_second_largest_node_testSuite.py\\nfind_second_largest_node_testSuite.py.backup\\noutput.log\\nrun.sh\\nutils\\n\\n./__pycache__:\\nfind_second_largest_node.cpython-311.pyc\\nfind_second_largest_node_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./find_second_largest_node_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/find_second_largest_node/output.log",
            "language": "python"
        },
        {
            "id": "same_tree_283",
            "error_message": "\u274c\u203c Errore nel container same_tree_283 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/same_tree:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\nsame_tree.py\\nsame_tree_testSuite.py\\nsame_tree_testSuite.py.backup\\nutils\\n\\n./__pycache__:\\nsame_tree.cpython-311.pyc\\nsame_tree_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./same_tree_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/same_tree/output.log",
            "language": "python"
        },
        {
            "id": "unival_trees_284",
            "error_message": "\u274c\u203c Errore nel container unival_trees_284 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/unival_trees:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\nunival_trees.py\\nunival_trees_testSuite.py\\nunival_trees_testSuite.py.backup\\nutils\\n\\n./__pycache__:\\nunival_trees.cpython-311.pyc\\nunival_trees_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./unival_trees_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/unival_trees/output.log",
            "language": "python"
        },
        {
            "id": "zigzag_level_order_traversal_286",
            "error_message": "\u274c\u203c Errore nel container zigzag_level_order_traversal_286 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/zigzag_level_order_traversal:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\nutils\\nzigzag_level_order_traversal.py\\nzigzag_level_order_traversal_testSuite.py\\nzigzag_level_order_traversal_testSuite.py.backup\\n\\n./__pycache__:\\nzigzag_level_order_traversal.cpython-311.pyc\\nzigzag_level_order_traversal_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./zigzag_level_order_traversal_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/zigzag_level_order_traversal/output.log",
            "language": "python"
        },
        {
            "id": "valid_bst_285",
            "error_message": "\u274c\u203c Errore nel container valid_bst_285 -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/valid_bst:/app', 'test_python_persistant'], returncode=1, stdout='==> Working dir:\\n/app\\n==> File structure:\\n.:\\n__pycache__\\noutput.log\\nrun.sh\\nutils\\nvalid_bst.py\\nvalid_bst_testSuite.py\\nvalid_bst_testSuite.py.backup\\n\\n./__pycache__:\\nvalid_bst.cpython-311.pyc\\nvalid_bst_testSuite.cpython-311.pyc\\n\\n./utils:\\n__init__.py\\n__pycache__\\nlist\\nlistutil.py\\nnarytree\\nquadtree\\ntree\\n\\n./utils/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/list:\\nListNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/list/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/narytree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/narytree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/quadtree:\\nNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/quadtree/__pycache__:\\n__init__.cpython-311.pyc\\n\\n./utils/tree:\\nTreeNode.py\\n__init__.py\\n__pycache__\\n\\n./utils/tree/__pycache__:\\n__init__.cpython-311.pyc\\n==> Looking for Python test files...\\n./valid_bst_testSuite.py\\n==> Running tests...\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/python/valid_bst/output.log",
            "language": "python"
        },
        {
            "id": "javascript_beer-song_exercism-javascript-ThomasZumsteg",
            "error_message": "\u274c\u203c Errore nel container javascript_beer-song_exercism-javascript-ThomasZumsteg -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/beer-song_exercism-javascript-ThomasZumsteg:/app', 'test_javascript_persistant'], returncode=1, stdout='\ud83d\udd75\ufe0f  Analisi file JS per determinare se usare ESM o CommonJS...\\n\u2699\ufe0f  Rilevato codice con import/export \u2192 ESM\\n\\nup to date, audited 266 packages in 9s\\n\\n32 packages are looking for funding\\n  run `npm fund` for details\\n\\nfound 0 vulnerabilities\\n\u25b6\ufe0f  Avvio Jest in modalit\u00e0 ESM\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/beer-song_exercism-javascript-ThomasZumsteg/output.log",
            "language": "javascript"
        },
        {
            "id": "javascript_acronym_exercism-javascript-ThomasZumsteg",
            "error_message": "\u274c\u203c Errore nel container javascript_acronym_exercism-javascript-ThomasZumsteg -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/acronym_exercism-javascript-ThomasZumsteg:/app', 'test_javascript_persistant'], returncode=1, stdout='\ud83d\udd75\ufe0f  Analisi file JS per determinare se usare ESM o CommonJS...\\n\u2699\ufe0f  Rilevato codice con import/export \u2192 ESM\\n\\nup to date, audited 266 packages in 8s\\n\\n32 packages are looking for funding\\n  run `npm fund` for details\\n\\nfound 0 vulnerabilities\\n\u25b6\ufe0f  Avvio Jest in modalit\u00e0 ESM\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/acronym_exercism-javascript-ThomasZumsteg/output.log",
            "language": "javascript"
        },
        {
            "id": "javascript_clock_exercism-javascript-ThomasZumsteg",
            "error_message": "\u274c\u203c Errore nel container javascript_clock_exercism-javascript-ThomasZumsteg -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/clock_exercism-javascript-ThomasZumsteg:/app', 'test_javascript_persistant'], returncode=1, stdout='\ud83d\udd75\ufe0f  Analisi file JS per determinare se usare ESM o CommonJS...\\n\u2699\ufe0f  Rilevato codice con import/export \u2192 ESM\\n\\nup to date, audited 266 packages in 8s\\n\\n32 packages are looking for funding\\n  run `npm fund` for details\\n\\nfound 0 vulnerabilities\\n\u25b6\ufe0f  Avvio Jest in modalit\u00e0 ESM\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/clock_exercism-javascript-ThomasZumsteg/output.log",
            "language": "javascript"
        },
        {
            "id": "javascript_hamming_exercism-javascript-ThomasZumsteg",
            "error_message": "\u274c\u203c Errore nel container javascript_hamming_exercism-javascript-ThomasZumsteg -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/hamming_exercism-javascript-ThomasZumsteg:/app', 'test_javascript_persistant'], returncode=1, stdout='\ud83d\udd75\ufe0f  Analisi file JS per determinare se usare ESM o CommonJS...\\n\u2699\ufe0f  Rilevato codice con import/export \u2192 ESM\\n\\nup to date, audited 266 packages in 8s\\n\\n32 packages are looking for funding\\n  run `npm fund` for details\\n\\nfound 0 vulnerabilities\\n\u25b6\ufe0f  Avvio Jest in modalit\u00e0 ESM\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/hamming_exercism-javascript-ThomasZumsteg/output.log",
            "language": "javascript"
        },
        {
            "id": "javascript_spiral-matrix_exercism-javascript-ThomasZumsteg",
            "error_message": "\u274c\u203c Errore nel container javascript_spiral-matrix_exercism-javascript-ThomasZumsteg -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/spiral-matrix_exercism-javascript-ThomasZumsteg:/app', 'test_javascript_persistant'], returncode=1, stdout='\ud83d\udd75\ufe0f  Analisi file JS per determinare se usare ESM o CommonJS...\\n\u2699\ufe0f  Rilevato codice con import/export \u2192 ESM\\n\\nup to date, audited 266 packages in 9s\\n\\n32 packages are looking for funding\\n  run `npm fund` for details\\n\\nfound 0 vulnerabilities\\n\u25b6\ufe0f  Avvio Jest in modalit\u00e0 ESM\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/spiral-matrix_exercism-javascript-ThomasZumsteg/output.log",
            "language": "javascript"
        },
        {
            "id": "javascript_wordy_exercism-javascript-ThomasZumsteg",
            "error_message": "\u274c\u203c Errore nel container javascript_wordy_exercism-javascript-ThomasZumsteg -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/wordy_exercism-javascript-ThomasZumsteg:/app', 'test_javascript_persistant'], returncode=1, stdout='\ud83d\udd75\ufe0f  Analisi file JS per determinare se usare ESM o CommonJS...\\n\u2699\ufe0f  Rilevato codice con import/export \u2192 ESM\\n\\nup to date, audited 266 packages in 8s\\n\\n32 packages are looking for funding\\n  run `npm fund` for details\\n\\nfound 0 vulnerabilities\\n\u25b6\ufe0f  Avvio Jest in modalit\u00e0 ESM\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/wordy_exercism-javascript-ThomasZumsteg/output.log",
            "language": "javascript"
        },
        {
            "id": "javascript_grade-school_exercism-javascript-PhymasSC",
            "error_message": "\u274c\u203c Errore nel container javascript_grade-school_exercism-javascript-PhymasSC -  | result:\nCompletedProcess(args=['docker', 'run', '--rm', '-v', '/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/grade-school_exercism-javascript-PhymasSC:/app', 'test_javascript_persistant'], returncode=1, stdout='\ud83d\udd75\ufe0f  Analisi file JS per determinare se usare ESM o CommonJS...\\n\u2699\ufe0f  Rilevato codice con import/export \u2192 ESM\\n\\nup to date, audited 266 packages in 7s\\n\\n32 packages are looking for funding\\n  run `npm fund` for details\\n\\nfound 0 vulnerabilities\\n\u25b6\ufe0f  Avvio Jest in modalit\u00e0 ESM\\n')\n",
            "log_file_path": "/Users/mars/Desktop/Everything/Pisa/tesi/src/dataset/javascript/grade-school_exercism-javascript-PhymasSC/output.log",
            "language": "javascript"
        }
    ]
}